//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CAE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap bug {
            get {
                object obj = ResourceManager.GetObject("bug", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.0
        ///3
        ///1       SQLCHAR       2       20      &quot;&quot;   1     project_nm                         SQL_Latin1_General_CP1_CI_AS
        ///2       SQLCHAR       2       50      &quot;&quot;   2     codefile_nm                        SQL_Latin1_General_CP1_CI_AS
        ///3       SQLDATETIME   0       8       &quot;&quot;   3     last_update_dtm                    &quot;&quot;
        ///.
        /// </summary>
        internal static string CodefileFormat {
            get {
                return ResourceManager.GetString("CodefileFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap exit {
            get {
                object obj = ResourceManager.GetObject("exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileclose {
            get {
                object obj = ResourceManager.GetObject("fileclose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filenew {
            get {
                object obj = ResourceManager.GetObject("filenew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fileopen {
            get {
                object obj = ResourceManager.GetObject("fileopen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesave {
            get {
                object obj = ResourceManager.GetObject("filesave", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap filesaveas {
            get {
                object obj = ResourceManager.GetObject("filesaveas", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.0
        ///2
        ///1       SQLCHAR       2       20      &quot;&quot;   1     project_nm                         SQL_Latin1_General_CP1_CI_AS
        ///2       SQLDATETIME   0       8       &quot;&quot;   2     last_update_dtm                    &quot;&quot;
        ///.
        /// </summary>
        internal static string ProjectFormat {
            get {
                return ResourceManager.GetString("ProjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.0
        ///7
        ///1       SQLCHAR       2       20      &quot;&quot;   1     project_nm                           SQL_Latin1_General_CP1_CI_AS
        ///2       SQLCHAR       2       50      &quot;&quot;   2     codefile_nm                          SQL_Latin1_General_CP1_CI_AS
        ///3       SQLINT        0       4       &quot;&quot;   3     codefile_line_no                     &quot;&quot;
        ///4       SQLCHAR       2       20      &quot;&quot;   4     rvwr_last_nm                         SQL_Latin1_General_CP1_CI_AS
        ///5       SQLCHAR       2       20      &quot;&quot;   5     rvwr_first_nm     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewAnnotationFormat {
            get {
                return ResourceManager.GetString("ReviewAnnotationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.0
        ///5
        ///1       SQLCHAR       2       20      &quot;&quot;   1     project_nm                           SQL_Latin1_General_CP1_CI_AS
        ///2       SQLCHAR       2       20      &quot;&quot;   2     rvwr_last_nm                         SQL_Latin1_General_CP1_CI_AS
        ///3       SQLCHAR       2       20      &quot;&quot;   3     rvwr_first_nm                        SQL_Latin1_General_CP1_CI_AS
        ///4       SQLCHAR       2       15      &quot;&quot;   4     annotation_color                     SQL_Latin1_General_CP1_CI_AS
        ///5       SQLDATETIME   0       8       &quot;&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ReviewerFormat {
            get {
                return ResourceManager.GetString("ReviewerFormat", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
